name: screenshare

services:
  server:
    container_name: simple-screenshare
    image: ghcr.io/kiralysanyi/simple-screenshare:testing # or :latest for a kinda stable version
    networks:
      vlan_net:
        ipv4_address: 192.168.1.20
    restart: unless-stopped
    healthcheck:
      disable: false
    environment:
      - HOST_PASS_ENABLE=1 # optional
      - HOST_PASS=valamijelszo # optional
      - ANNOUNCED_IP=192.168.1.20 # ip to announce for clients (should be accessable from all clients, or else you will get blank video)
      - HTTP_PORT=8888 # port of the http server
      - RTC_MIN_PORT=40000 #optional RTC min udp port default: 40000
      - RTC_MAX_PORT=40500 #optional RTC max udp port default: 40500

networks:
  vlan_net:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1